<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCrhehlp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCrhehlp/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCrhehlp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCrhehlp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCrhehlp\appProdProjectContainer([
    'container.build_hash' => 'Crhehlp',
    'container.build_id' => '8e0feec2',
    'container.build_time' => 1551316037,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCrhehlp');
